version: "3"
services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
  app:
    build: 
      context: .
      dockerfile: appDockerfile
    labels:
      - "traefik.backend=app-be"
      - "traefik.frontend.rule=Host:app.localhost"
  blog:
    build: 
      context: .
      dockerfile: blogDockerfile
    labels:
      - "traefik.backend=blog-be"
      - "traefik.frontend.rule=Host:blog.localhost"
  website:
    build: 
      context: .
      dockerfile: websiteDockerfile
    labels:
      - "traefik.backend=website-be"
      - "traefik.frontend.rule=Host:website.localhost"
